meta_product_name: "Yarnlore"
meta_title: "Yarnlore - Crafting Dreams"
meta_description: "Discover and track your favourite patterns"
meta_image: "knitting.png"
twitter_account: "@product_twitter_account"
